'use client';
import {useEffect,useMemo,useState} from 'react';
import {ArrowLeft,CheckCircle2,ClipboardList,Plus,RefreshCw,Send,UserRound} from 'lucide-react';
import type {State,Task} from '@/lib/domain';
import {useLang} from '../use-lang';
type Actor={id:string;admin:boolean};
const today=()=>new Intl.DateTimeFormat('en-CA',{timeZone:'America/New_York',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
export default function TaskInbox(){
 const {t,locale}=useLang();
 const [state,setState]=useState<State|null>(null);const [actor,setActor]=useState<Actor>({id:'admin',admin:true});const [version,setVersion]=useState(0);const [setup,setSetup]=useState(false);const [error,setError]=useState('');const [busy,setBusy]=useState(false);const [form,setForm]=useState({assignedTo:'',title:'',notes:'',date:today()});
 const query=()=>window.location.search;
 // /tasks is also rendered on the server, where window does not exist; the team query is filled in after mount.
 const [root,setRoot]=useState('/');
 const receive=(data:any)=>{if(data.state){setState({...data.state,tasks:data.state.tasks??[]});setVersion(data.version);setSetup(false)}else setSetup(true);if(data.actor)setActor(data.actor)};
 async function refresh(){try{const r=await fetch('/api/workspace'+query());const data=await r.json();if(!r.ok)throw Error(data.error||'작업을 불러오지 못했습니다.');receive(data);setError('')}catch(e){setError(e instanceof Error?e.message:'작업을 불러오지 못했습니다.')}}
 useEffect(()=>{setRoot('/'+query());void refresh()},[]);
 async function send(type:string,payload:Record<string,string>){if(!state)return;setBusy(true);try{const r=await fetch('/api/workspace'+query(),{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({type,payload,version})});const data=await r.json();if(!r.ok)throw Error(data.error||'저장하지 못했습니다.');receive(data);setError('')}catch(e){setError(e instanceof Error?e.message:'저장하지 못했습니다.')}finally{setBusy(false)}}
 const employees=state?.employees??[];const tasks=useMemo(()=>[...(state?.tasks??[])].sort((a,b)=>a.status==='completed'&&b.status!=='completed'?1:a.date.localeCompare(b.date)),[state]);
 const employee=(id:string)=>employees.find(e=>e.id===id);
 // Managers and staff with task permission can assign tasks; everyone works on the tasks assigned to them.
 const canAssign=actor.admin||!!employee(actor.id)?.taskManager;
 const status=(task:Task)=>task.status==='completed'?[t('완료'),'done']:task.status==='seen'?[t('status::확인'),'seen']:[t('새 작업'),'sent'];
 if(error&&!state)return <main className="task-shell"><section className="task-card error-card"><ClipboardList size={30}/><h1>{t('작업 수신함')}</h1><p>{t(error)}</p><a className="task-button" href={root}>{t('로그인하고 열기')}</a></section></main>;
 return <main className="task-shell"><header className="task-top"><a href={root} className="back"><ArrowLeft size={17}/> {t('스케줄')}</a><div><p>PELHAM SHIFT</p><h1>{canAssign?t('작업 지시 관리'):t('내 작업 수신함')}</h1></div><span className="task-top-actions"><button className="refresh" onClick={()=>void refresh()} aria-label={t('새로고침')}><RefreshCw size={18}/></button></span></header>
 {error&&<p role="alert" className="task-alert">{t(error)}</p>}
 {setup?<section className="task-card"><ClipboardList size={32}/><h2>{t('워크스페이스를 먼저 생성하세요')}</h2><p>{t('관리자 화면에서 ‘내 워크스페이스 생성’을 누르면 작업 지시를 시작할 수 있습니다.')}</p><a className="task-button" href={root}>{t('스케줄로 이동')}</a></section>:<>
 {canAssign&&<section className="task-compose"><div><span className="task-kicker">MANAGER</span><h2>{t('직원에게 작업 지시 보내기')}</h2><p>{t('직원은 수신함에서 확인과 완료 처리를 할 수 있습니다.')}</p></div><form onSubmit={e=>{e.preventDefault();void send('taskCreate',form).then(()=>setForm({assignedTo:'',title:'',notes:'',date:today()}))}}><label>{t('받는 직원')}<select required value={form.assignedTo} onChange={e=>setForm(f=>({...f,assignedTo:e.target.value}))}><option value="">{t('직원을 선택하세요')}</option>{employees.map(e=><option value={e.id} key={e.id}>{e.name} · {e.role}</option>)}</select></label><label>{t('마감일')}<input type="date" required value={form.date} onChange={e=>setForm(f=>({...f,date:e.target.value}))}/></label><label className="wide">{t('작업 제목')}<input maxLength={160} required placeholder={t('예: 3번 홀 장비 점검')} value={form.title} onChange={e=>setForm(f=>({...f,title:e.target.value}))}/></label><label className="wide">{t('작업 안내')}<textarea maxLength={2000} placeholder={t('필요한 준비물, 완료 기준 등을 적어주세요.')} value={form.notes} onChange={e=>setForm(f=>({...f,notes:e.target.value}))}/></label><button className="task-button" disabled={busy}><Send size={16}/> {t('작업 보내기')}</button></form></section>}
 <section className="task-list"><div className="task-list-head"><div><span className="task-kicker">{canAssign?'TEAM TASKS':'ASSIGNED TO ME'}</span><h2>{t('{n}개의 진행 중 작업',{n:tasks.filter(t=>t.status!=='completed').length})}</h2></div>{canAssign&&<span className="task-count">{t('전체 {n}건',{n:tasks.length})}</span>}</div>{tasks.map(task=>{const person=employee(task.assignedTo);const [label,tone]=status(task);return <article className={'task-item '+tone} key={task.id}><div className="task-status"><CheckCircle2 size={21}/></div><div className="task-main"><div className="task-meta"><span className={'task-badge '+tone}>{label}</span><time>{t('마감 {date}',{date:task.date})}</time></div><h3>{task.title}</h3>{task.notes&&<p>{task.notes}</p>}<div className="task-person"><UserRound size={14}/><i style={{background:person?.color}}/>{person?.name||t('직원')}{task.createdBy&&employee(task.createdBy)&&<span>{t('· {name} 지시',{name:employee(task.createdBy)?.name||t('직원')})}</span>}{task.completedAt&&<span>{t('· {time} 완료',{time:new Date(task.completedAt).toLocaleString(locale,{timeZone:'America/New_York'})})}</span>}</div></div>{task.assignedTo===actor.id&&task.status==='sent'&&<button className="task-outline" disabled={busy} onClick={()=>void send('taskUpdate',{id:task.id,action:'seen'})}>{t('확인')}</button>}{task.assignedTo===actor.id&&task.status!=='completed'&&<button className="task-button compact" disabled={busy} onClick={()=>void send('taskUpdate',{id:task.id,action:'complete'})}><CheckCircle2 size={15}/> {t('완료 처리')}</button>}</article>})}{!tasks.length&&<div className="task-empty"><ClipboardList size={32}/><h3>{actor.admin?t('보낸 작업이 없습니다'):t('새로 받은 작업이 없습니다')}</h3><p>{actor.admin?t('위 양식에서 직원에게 첫 작업을 보내세요.'):t('새 작업이 오면 이곳에서 바로 확인할 수 있습니다.')}</p></div>}</section></>}
 </main>
}
