'use client';
import {useEffect,useMemo,useState} from 'react';
import {ArrowLeft,CheckCircle2,ClipboardList,Plus,RefreshCw,Send,Trash2,UserRound} from 'lucide-react';
import type {State,Task} from '@/lib/domain';
import {TIME_ZONE,areaList,roleLabel,roleList} from '@/lib/domain';
import {notice} from '@/lib/notice';
import {useLang} from '../use-lang';
import TimePicker from '../time-picker';
type Actor={id:string;admin:boolean};
const today=()=>new Intl.DateTimeFormat('en-CA',{timeZone:TIME_ZONE,year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
// 마감 시각은 10분 단위로만 섭니다 — 서버도 같은 눈금으로 받습니다.
const MINUTE_STEP=10;
// 화면에 보이는 시각. 시계에서 고른 것만 들어오므로 어긋난 값은 빈 칸으로 두고 --:-- 가 드러납니다.
const clockText=(v:string)=>{if(!/^([01]\d|2[0-3]):[0-5]\d$/.test(v))return '';const h=Number(v.slice(0,2));return `${h%12||12}:${v.slice(3,5)} ${h<12?'AM':'PM'}`};
export default function TaskInbox(){
 const {t,locale}=useLang();
 const [state,setState]=useState<State|null>(null);const [actor,setActor]=useState<Actor>({id:'admin',admin:true});const [version,setVersion]=useState(0);const [setup,setSetup]=useState(false);const [error,setError]=useState('');const [busy,setBusy]=useState(false);const [form,setForm]=useState({assignedTo:'',title:'',notes:'',date:today(),time:''});const [area,setArea]=useState('');const [clock,setClock]=useState(false);const [saved,setSaved]=useState('');
 const query=()=>window.location.search;
 // /tasks is also rendered on the server, where window does not exist; the team query is filled in after mount.
 const [root,setRoot]=useState('/');
 const receive=(data:any)=>{if(data.state){setState({...data.state,tasks:data.state.tasks??[]});setVersion(data.version);setSetup(false)}else setSetup(true);if(data.actor)setActor(data.actor)};
 async function refresh(){setSaved('');try{const r=await fetch('/api/workspace'+query());const data=await r.json();if(!r.ok)throw Error(data.error||'작업을 불러오지 못했습니다.');receive(data);setError('')}catch(e){setError(notice(e,'작업을 불러오지 못했습니다.'))}}
 useEffect(()=>{setRoot('/'+query());void refresh()},[]);
 // 저장 알림은 4초만 머뭅니다. 알림이 바뀌면 이전 타이머는 걷어 냅니다.
 useEffect(()=>{if(!saved)return;const timer=setTimeout(()=>setSaved(''),4000);return ()=>clearTimeout(timer)},[saved]);
 // 보낸 뒤 입력칸을 비울지는 성공했을 때만 정합니다 — 이름이 겹쳐 되돌아온 글자를 다시 치게 하지 않으려고요.
 async function send(type:string,payload:Record<string,string>){if(!state)return false;setSaved('');setBusy(true);try{const r=await fetch('/api/workspace'+query(),{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({type,payload,version})});const data=await r.json();if(!r.ok)throw Error(data.error||'저장하지 못했습니다.');receive(data);setError('');return true}catch(e){setError(notice(e,'저장하지 못했습니다.'));return false}finally{setBusy(false)}}
 const employees=state?.employees??[];
 // 받는 사람 목록은 이름과 직군만 보여 줍니다 — 직원 ID 는 이 화면에 적지 않습니다.
 // 지운 직원은 목록에서 빠지고, 같은 직군끼리 모여 보이도록 직군·이름 순으로 세웁니다.
 const assignable=useMemo(()=>(state?.employees??[]).filter(e=>!e.archived).sort((a,b)=>(roleList(a)[0]||'').localeCompare(roleList(b)[0]||'')||a.name.localeCompare(b.name)),[state]);const areas=state?areaList(state):[];const tasks=useMemo(()=>[...(state?.tasks??[])].sort((a,b)=>a.status==='completed'&&b.status!=='completed'?1:a.date.localeCompare(b.date)),[state]);
 const employee=(id:string)=>employees.find(e=>e.id===id);
 // Managers and staff with task permission can assign tasks; everyone works on the tasks assigned to them.
 const canAssign=actor.admin||!!employee(actor.id)?.taskManager;
 // 작업 지시는 낸 사람이 거두어 갑니다. 관리자는 누가 낸 것이든 지울 수 있습니다.
 const canRemove=(task:Task)=>actor.admin||(!!task.createdBy&&task.createdBy===actor.id);
 const status=(task:Task)=>task.status==='completed'?[t('완료'),'done']:task.status==='seen'?[t('status::확인'),'seen']:[t('새 작업'),'sent'];
 if(error&&!state)return <main className="task-shell"><section className="task-card error-card"><ClipboardList size={30}/><h1>{t('작업 수신함')}</h1><p>{t(error)}</p><a className="task-button" href={root}>{t('로그인하고 열기')}</a></section></main>;
 return <main className="task-shell"><header className="task-top"><a href={root} className="back"><ArrowLeft size={17}/> {t('스케줄')}</a><div><p>PELHAM SHIFT</p><h1>{canAssign?t('작업 지시 관리'):t('내 작업 수신함')}</h1></div><span className="task-top-actions"><button className="refresh" onClick={()=>void refresh()} aria-label={t('새로고침')}><RefreshCw size={18}/></button></span></header>
 {error&&<p role="alert" className="task-alert">{t(error)}</p>}
 {saved&&<div className="inapp-alert" role="status"><span className="inapp-icon"><CheckCircle2 size={18}/></span><div><b>{t('저장했습니다.')}</b><p>{t('‘{name}’ 업무를 목록에 더했습니다.',{name:saved})}</p></div><span className="inapp-actions"><button className="task-outline compact" onClick={()=>setSaved('')}>{t('닫기')}</button></span></div>}
 {setup?<section className="task-card"><ClipboardList size={32}/><h2>{t('워크스페이스를 먼저 생성하세요')}</h2><p>{t('관리자 화면에서 ‘내 워크스페이스 생성’을 누르면 작업 지시를 시작할 수 있습니다.')}</p><a className="task-button" href={root}>{t('스케줄로 이동')}</a></section>:<>
 {canAssign&&<section className="task-compose"><div><span className="task-kicker">MANAGER</span><h2>{t('직원에게 작업 지시 보내기')}</h2><p>{t('직원은 수신함에서 확인과 완료 처리를 할 수 있습니다.')}</p></div><form onSubmit={e=>{e.preventDefault();void send('taskCreate',form).then(ok=>{if(ok)setForm({assignedTo:'',title:'',notes:'',date:today(),time:''})})}}><label>{t('받는 직원')}<select required value={form.assignedTo} onChange={e=>setForm(f=>({...f,assignedTo:e.target.value}))}><option value="">{t('직원을 선택하세요')}</option>{assignable.map(e=><option value={e.id} key={e.id}>{roleLabel(e)?`${e.name} · ${roleLabel(e)}`:e.name}</option>)}</select></label><label>{t('마감일')}<input type="date" required value={form.date} onChange={e=>setForm(f=>({...f,date:e.target.value}))}/></label><label>{t('마감 시각')}<input type="text" inputMode="none" className="timepick" placeholder="--:--" value={clockText(form.time)} aria-label={t('마감 시각')} onKeyDown={e=>{e.preventDefault();if(e.key==='Enter'||e.key===' ')setClock(true);else if(e.key==='Backspace'||e.key==='Delete')setForm(f=>({...f,time:''}))}} onMouseDown={e=>e.preventDefault()} onClick={()=>setClock(true)} onChange={()=>undefined}/><small className="task-timenote">{form.time?<button type="button" onClick={()=>setForm(f=>({...f,time:''}))}>{t('시각 비우기')}</button>:t('적지 않아도 됩니다')}</small></label><label className="wide">{t('작업 제목')}<input maxLength={160} required placeholder={t('예: 3번 홀 장비 점검')} value={form.title} onChange={e=>setForm(f=>({...f,title:e.target.value}))}/></label><label className="wide">{t('작업 안내')}<textarea maxLength={2000} placeholder={t('필요한 준비물, 완료 기준 등을 적어주세요.')} value={form.notes} onChange={e=>setForm(f=>({...f,notes:e.target.value}))}/></label><button className="task-button" disabled={busy}><Send size={16}/> {t('작업 보내기')}</button></form>{clock&&<TimePicker value={form.time} label={t('마감 시각')} minuteStep={MINUTE_STEP} onCancel={()=>setClock(false)} onPick={v=>{setForm(f=>({...f,time:v}));setClock(false)}}/>}</section>}
 {/* 업무(직무)는 여기서만 늘립니다 — 관리자도 작업 지시 권한을 가진 직원도 닿는 화면이 이곳뿐입니다. */}
 {canAssign&&<section className="task-compose task-areas"><div><span className="task-kicker">JOBS</span><h2>{t('업무 목록')}</h2><p>{t('여기에 더한 업무는 직원 정보와 근무 추가 화면의 업무 선택지에 바로 나타납니다.')}</p></div><ul className="task-areachips">{areas.map(a=><li key={a}>{a}</li>)}</ul><form onSubmit={e=>{e.preventDefault();const name=area.trim();void send('areaAdd',{name:area}).then(ok=>{if(ok){setArea('');setSaved(name)}})}}><label>{t('새 업무 이름')}<input maxLength={60} required placeholder={t('예: Kitchen')} value={area} onChange={e=>setArea(e.target.value)}/></label><button className="task-button" disabled={busy}><Plus size={16}/> {t('업무 추가')}</button></form></section>}
 <section className="task-list"><div className="task-list-head"><div><span className="task-kicker">{canAssign?'TEAM TASKS':'ASSIGNED TO ME'}</span><h2>{t('{n}개의 진행 중 작업',{n:tasks.filter(t=>t.status!=='completed').length})}</h2></div>{canAssign&&<span className="task-count">{t('전체 {n}건',{n:tasks.length})}</span>}</div>{tasks.map(task=>{const person=employee(task.assignedTo);const [label,tone]=status(task);return <article className={'task-item '+tone} key={task.id}><div className="task-status"><CheckCircle2 size={21}/></div><div className="task-main"><div className="task-meta"><span className={'task-badge '+tone}>{label}</span><time>{task.time?t('마감 {date} {time}',{date:task.date,time:clockText(task.time)}):t('마감 {date}',{date:task.date})}</time></div><h3>{task.title}</h3>{task.notes&&<p>{task.notes}</p>}<div className="task-person"><UserRound size={14}/><i style={{background:person?.color}}/>{person?.name||t('직원')}{task.createdBy&&employee(task.createdBy)&&<span>{t('· {name} 지시',{name:employee(task.createdBy)?.name||t('직원')})}</span>}{task.completedAt&&<span>{t('· {time} 완료',{time:new Date(task.completedAt).toLocaleString(locale,{timeZone:TIME_ZONE})})}</span>}</div></div>{task.assignedTo===actor.id&&task.status==='sent'&&<button className="task-outline" disabled={busy} onClick={()=>void send('taskUpdate',{id:task.id,action:'seen'})}>{t('확인')}</button>}{task.assignedTo===actor.id&&task.status!=='completed'&&<button className="task-button compact" disabled={busy} onClick={()=>void send('taskUpdate',{id:task.id,action:'complete'})}><CheckCircle2 size={15}/> {t('완료 처리')}</button>}{canRemove(task)&&<button className="task-outline" disabled={busy} onClick={()=>{if(confirm(t('이 작업 지시를 삭제할까요? 받은 직원의 수신함에서도 사라집니다.')))void send('taskRemove',{id:task.id})}}><Trash2 size={15}/> {t('삭제')}</button>}</article>})}{!tasks.length&&<div className="task-empty"><ClipboardList size={32}/><h3>{actor.admin?t('보낸 작업이 없습니다'):t('새로 받은 작업이 없습니다')}</h3><p>{actor.admin?t('위 양식에서 직원에게 첫 작업을 보내세요.'):t('새 작업이 오면 이곳에서 바로 확인할 수 있습니다.')}</p></div>}</section></>}
 </main>
}
