import {type State,type Shift,type Attendance,canSwap,overlap,duration} from './domain';
export type Actor={id:string;admin:boolean};
export type Command={type:string;payload:any};
const fail=(message:string):never=>{throw new Error(message)};
function text(value:unknown,max=200){if(typeof value!=='string'||!value.trim()||value.length>max)fail('필수 입력값을 확인하세요.');return (value as string).trim()}
function date(value:string){if(!/^\d{4}-\d{2}-\d{2}$/.test(value)||new Date(value+'T12:00Z').toISOString().slice(0,10)!==value)fail('날짜를 확인하세요.');return value}
function time(value:string){if(!/^([01]\d|2[0-3]):[0-5]\d$/.test(value))fail('시간 형식을 확인하세요.');return value}
function number(value:unknown,max=1000000){const n=Number(value);if(!Number.isFinite(n)||n<0||n>max)fail('0 이상의 유효한 금액/시간을 입력하세요.');return n}
export function applyCommand(current:State,command:Command,actor:Actor,now=new Date()):State{
 const s=structuredClone(current),p=command.payload??{},id=()=>crypto.randomUUID();s.tasks??=[];const admin=()=>{if(!actor.admin)fail('관리자 권한이 필요합니다.')};const employee=(v:string)=>s.employees.find(e=>e.id===v)??fail('등록된 직원을 선택하세요.');
 switch(command.type){
 case 'employee': {admin();const e={id:p.id||id(),name:text(p.name,80),color:text(p.color,7),role:text(p.role,60),email:String(p.email||'').trim().toLowerCase(),rate:number(p.rate)};if(!/^#[0-9a-f]{6}$/i.test(e.color))fail('직원 색상을 확인하세요.');if(e.email&&!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(e.email))fail('이메일을 확인하세요.');if(e.email&&s.employees.some(x=>x.id!==e.id&&x.email===e.email))fail('이미 등록된 이메일입니다.');s.employees=s.employees.filter(x=>x.id!==e.id).concat(e);break;}
 case 'shift': {admin();employee(p.employeeId);const shift:Shift={id:id(),employeeId:p.employeeId,date:date(p.date),start:time(p.start),end:time(p.end),area:text(p.area,60)};if(!duration(shift.start,shift.end))fail('출근과 퇴근 시간이 같습니다.');if(s.shifts.some(x=>x.employeeId===shift.employeeId&&overlap(x,shift)))fail('해당 직원의 근무시간이 겹칩니다.');s.shifts.push(shift);s.published=false;break;}
 case 'publish':admin();s.published=true;break;
 case 'currency':admin();if(!['USD','CAD','KRW','PHP'].includes(p.currency))fail('통화를 선택하세요.');s.currency=p.currency;break;
 case 'swap': {const shift=s.shifts.find(x=>x.id===p.shiftId)??fail('근무를 선택하세요.');if(!actor.admin&&shift.employeeId!==actor.id)fail('본인 근무만 대체 신청할 수 있습니다.');if(!canSwap(shift.date))fail('대체 신청은 근무일 7일 전까지 가능합니다.');employee(p.to);if(p.to===shift.employeeId)fail('다른 대체 직원을 선택하세요.');if(shift.originalId)fail('이미 대체 승인된 근무입니다.');if(s.swaps.some(x=>x.shiftId===shift.id&&x.status!=='rejected'))fail('이미 대체 요청이 있습니다.');if(s.shifts.some(x=>x.employeeId===p.to&&overlap(x,shift)))fail('대체 직원의 기존 근무시간과 겹칩니다.');s.swaps.push({id:id(),shiftId:shift.id,from:shift.employeeId,to:p.to,status:'requested',createdAt:now.toISOString(),bonus:0});break;}
 case 'swapDecision': {const r=s.swaps.find(x=>x.id===p.id)??fail('요청을 찾을 수 없습니다.');if(p.action==='accept'){if(actor.admin||actor.id!==r.to)fail('대체 직원 본인이 수락해야 합니다.');if(r.status!=='requested')fail('처리된 요청입니다.');r.status='accepted'}else if(p.action==='reject'){if(!actor.admin&&actor.id!==r.to&&actor.id!==r.from)fail('권한이 없습니다.');if(r.status==='approved')fail('승인된 대체는 취소할 수 없습니다.');r.status='rejected'}else if(p.action==='approve'){admin();if(r.status!=='accepted')fail('대체 직원의 수락이 먼저 필요합니다.');const shift=s.shifts.find(x=>x.id===r.shiftId)??fail('근무가 없습니다.');if(!canSwap(shift.date))fail('대체 승인도 근무일 7일 전까지 가능합니다.');if(shift.employeeId!==r.from)fail('원래 근무자가 변경되었습니다.');if(s.shifts.some(x=>x.id!==shift.id&&x.employeeId===r.to&&overlap(x,shift)))fail('대체 직원의 근무시간이 겹칩니다.');shift.originalId=r.from;shift.employeeId=r.to;r.bonus=number(p.bonus);r.status='approved'}else fail('잘못된 처리입니다.');break;}
 case 'attendance': {admin();if(!Array.isArray(p.rows)||!p.rows.length||p.rows.length>3000)fail('1~3,000개 행을 가져올 수 있습니다.');for(const row of p.rows){employee(row.employeeId);const a:Attendance={id:id(),employeeId:row.employeeId,date:date(row.date),start:time(row.start),end:time(row.end),breakMinutes:number(row.breakMinutes,1440)};if(!duration(a.start,a.end)||a.breakMinutes>=duration(a.start,a.end)*60)fail('퇴근 시간과 휴게시간을 확인하세요.');const shift={...a,area:''};if(s.attendance.some(x=>x.employeeId===a.employeeId&&overlap({...x,area:''},shift)))fail(`${a.date} ${a.employeeId}: 중복 또는 겹치는 출근기록입니다.`);s.attendance.push(a)}break;}
 case 'message': {if(p.to!=='admin'&&p.to!=='all')employee(p.to);if(p.to==='all')admin();s.messages.push({id:id(),sender:actor.id,to:p.to,body:text(p.body,2000),createdAt:now.toISOString(),readBy:[actor.id],kind:'message'});break;}
 case 'rain': {admin();const end=time(p.end);s.messages.push({id:id(),sender:actor.id,to:'all',body:`[우천 근무 종료] ${date(p.date)} ${end}에 전 직원 근무를 종료합니다. ${text(p.body,1000)}`,createdAt:now.toISOString(),readBy:[actor.id],kind:'rain'});break;}
 case 'read': {const m=s.messages.find(x=>x.id===p.id)??fail('메시지가 없습니다.');if(m.to!=='all'&&m.to!==actor.id&&m.sender!==actor.id)fail('권한이 없습니다.');if(!m.readBy.includes(actor.id))m.readBy.push(actor.id);break;}
 case 'taskCreate': {admin();const assignedTo=text(p.assignedTo,80);employee(assignedTo);s.tasks.push({id:id(),assignedTo,title:text(p.title,160),notes:typeof p.notes==='string'?p.notes.trim().slice(0,2000):'',date:date(p.date),status:'sent',createdAt:now.toISOString()});break;}
 case 'taskUpdate': {const task=s.tasks.find(x=>x.id===text(p.id,120))??fail('작업을 찾을 수 없습니다.');if(!actor.admin&&task.assignedTo!==actor.id)fail('본인에게 배정된 작업만 처리할 수 있습니다.');if(p.action==='seen'){if(task.status==='sent')task.status='seen'}else if(p.action==='complete'){task.status='completed';task.completedAt=now.toISOString()}else fail('잘못된 작업 처리입니다.');break;}
 default:fail('지원하지 않는 요청입니다.');
 }return s;
}
