import {env} from '@/lib/db';
import {buildPushPayload} from '@block65/webcrypto-web-push';
import {type State,TIME_ZONE,localDate,addDays,minutes} from './domain';
import {translate,isLang,SCREEN_LANG,type Vars} from './i18n';
export type Note={title:string;body:string;tag?:string;vars?:Vars};
type Keys={publicKey:string;privateKey:string;tickKey:string};
type Sub={endpoint:string;member:string;p256dh:string;auth:string;lang:string};
const b64url=(bytes:ArrayBuffer|Uint8Array)=>{let s='';for(const b of new Uint8Array(bytes))s+=String.fromCharCode(b);return btoa(s).replaceAll('+','-').replaceAll('/','_').replace(/=+$/,'')};
const selectKeys='SELECT public_key AS "publicKey", private_key AS "privateKey", tick_key AS "tickKey" FROM push_keys WHERE workspace = ?';
// VAPID keys live in the database per workspace, so the deploy needs no secret configuration.
export async function pushKeys(workspace:string):Promise<Keys>{const found=await env.DB.prepare(selectKeys).bind(workspace).first<Keys>();if(found)return found;const pair=await crypto.subtle.generateKey({name:'ECDSA',namedCurve:'P-256'},true,['sign','verify']) as CryptoKeyPair;const raw=await crypto.subtle.exportKey('raw',pair.publicKey) as ArrayBuffer;const jwk=await crypto.subtle.exportKey('jwk',pair.privateKey) as JsonWebKey;await env.DB.prepare('INSERT INTO push_keys (workspace,public_key,private_key,tick_key) VALUES (?,?,?,?) ON CONFLICT DO NOTHING').bind(workspace,b64url(raw),jwk.d,b64url(crypto.getRandomValues(new Uint8Array(24)))).run();return (await env.DB.prepare(selectKeys).bind(workspace).first<Keys>())!}
// Each device keeps the language it subscribed with, so its notifications arrive in the language its owner reads.
export async function subscribe(workspace:string,member:string,value:unknown,lang?:unknown){const v=value as {endpoint?:unknown;keys?:{p256dh?:unknown;auth?:unknown}}|null;const ok=(x:unknown,max:number):x is string=>typeof x==='string'&&x.length>0&&x.length<=max;if(!ok(v?.endpoint,1000)||!v.endpoint.startsWith('https://')||!ok(v.keys?.p256dh,200)||!ok(v.keys?.auth,100))throw new Error('알림 구독 정보를 확인하세요.');await env.DB.prepare('INSERT INTO push_subscriptions (endpoint,workspace,member,p256dh,auth,created_at,lang) VALUES (?,?,?,?,?,?,?) ON CONFLICT(endpoint) DO UPDATE SET workspace=excluded.workspace, member=excluded.member, p256dh=excluded.p256dh, auth=excluded.auth, created_at=excluded.created_at, lang=excluded.lang').bind(v.endpoint,workspace,member,v.keys.p256dh,v.keys.auth,new Date().toISOString(),isLang(lang)?lang:'en').run()}
export async function unsubscribe(workspace:string,member:string,endpoint:unknown){await env.DB.prepare('DELETE FROM push_subscriptions WHERE endpoint = ? AND workspace = ? AND member = ?').bind(typeof endpoint==='string'?endpoint:'',workspace,member).run()}
export async function notify(workspace:string,members:string[],note:Note,origin:string){const targets=new Set(members);const subs=(await env.DB.prepare('SELECT endpoint,member,p256dh,auth,lang FROM push_subscriptions WHERE workspace = ?').bind(workspace).all<Sub>()).results.filter(s=>targets.has(s.member));if(!subs.length)return 0;const keys=await pushKeys(workspace);const vapid={subject:origin.startsWith('https://')?origin:'mailto:notifications@pelham-shift.invalid',publicKey:keys.publicKey,privateKey:keys.privateKey};const url='/?team='+encodeURIComponent(workspace);// 알림도 화면과 같은 말로 갑니다. 기기마다 저장된 lang 은 언어 고르기가 돌아올 때를 위해 그대로 둡니다.
 const results=await Promise.allSettled(subs.map(async s=>{const lang=SCREEN_LANG;const data=JSON.stringify({title:translate(lang,note.title,note.vars),body:translate(lang,note.body,note.vars),tag:note.tag,url});const res=await fetch(s.endpoint,await buildPushPayload({data,options:{ttl:3600,urgency:'high'}},{endpoint:s.endpoint,expirationTime:null,keys:{p256dh:s.p256dh,auth:s.auth}},vapid));if(res.status===404||res.status===410)await env.DB.prepare('DELETE FROM push_subscriptions WHERE endpoint = ?').bind(s.endpoint).run();return res.ok}));return results.filter(r=>r.status==='fulfilled'&&r.value).length}
const clubMinutes=(now:Date)=>minutes(new Intl.DateTimeFormat('en-GB',{timeZone:TIME_ZONE,hour:'2-digit',minute:'2-digit',hourCycle:'h23'}).format(now));
export function dueShifts(state:State,now=new Date()){if(!state.published)return [];const today=localDate(now),tomorrow=addDays(today,1),current=clubMinutes(now);return state.shifts.filter(s=>{if(s.date!==today&&s.date!==tomorrow)return false;const diff=(s.date===today?0:1440)+minutes(s.start)-current;return diff>0&&diff<=60})}
// Each shift start is claimed in push_sent before sending, so concurrent polls and cron ticks never double-send.
// A claim whose send reached no device is released, so the next poll retries (e.g. the employee enables push later).
export async function remind(workspace:string,state:State,origin:string,now=new Date()){let sent=0;for(const s of dueShifts(state,now)){const id=`${workspace}:${s.id}:${s.employeeId}:${s.date}T${s.start}`;const claim=await env.DB.prepare('INSERT INTO push_sent (id,workspace,sent_at) VALUES (?,?,?) ON CONFLICT DO NOTHING').bind(id,workspace,now.toISOString()).run();if(claim.meta.changes!==1)continue;const n=await notify(workspace,[s.employeeId],{title:'출근 1시간 전 알림',body:'{date} {start} · {area} 근무가 1시간 이내에 시작됩니다.',vars:{date:s.date.slice(5).replace('-','/'),start:s.start,area:s.area},tag:'shift-'+s.id},origin).catch(()=>0);if(n)sent+=n;else await env.DB.prepare('DELETE FROM push_sent WHERE id = ?').bind(id).run()}if(sent)await env.DB.prepare('DELETE FROM push_sent WHERE workspace = ? AND sent_at < ?').bind(workspace,new Date(now.getTime()-7*86400000).toISOString()).run();return sent}
