import type {State} from '@/lib/domain';
import type {Actor} from '@/lib/operations';
import {getBirthSession} from '@/lib/birth-auth';
export const json=(value:unknown,status=200)=>Response.json(value,{status,headers:{'Cache-Control':'no-store'}});
export const sameOrigin=(req:Request)=>{const origin=req.headers.get('origin');return !origin||origin===new URL(req.url).origin};
// Only the birth-date session authenticates: ChatGPT identity headers are injected by Sites hosting and can be forged anywhere else.
export async function context(req:Request){const local=await getBirthSession(req);if(!local)return null;const user={userId:local.actor.admin?'master':local.actor.id,displayName:local.actor.admin?'대표님':'직원',email:'',fullName:null};return {user,team:local.team,row:local.row,state:local.state,actor:local.actor,authMethod:'birth',passwordChanged:local.passwordChanged}}
export function visible(state:State,actor:Actor){const tasks=state.tasks??[],timeOff=state.timeOff??[],availability=state.availability??[],punches=state.punches??[];if(actor.admin)return {...state,tasks,timeOff,availability,punches};const taskManager=!!state.employees.find(e=>e.id===actor.id)?.taskManager;return {...state,punches:punches.filter(r=>r.employeeId===actor.id),timeOff:timeOff.filter(r=>r.employeeId===actor.id),availability:availability.filter(r=>r.employeeId===actor.id),tasks:taskManager?tasks:tasks.filter(t=>t.assignedTo===actor.id),employees:state.employees.map(e=>e.id===actor.id?{...e,email:'',birthDate:'',phone:''}:{...e,email:'',birthDate:'',phone:'',rate:0}),shifts:state.published?state.shifts:[],attendance:state.attendance.filter(a=>a.employeeId===actor.id),swaps:[],
// Staff see what was sent to them (directly, to everyone, or to a notice list they are on) and what they sent; other staff's read receipts stay private.
messages:state.messages.filter(m=>m.sender===actor.id||m.to===actor.id||(m.to==='all'&&(!m.recipients||m.recipients.includes(actor.id)))).map(m=>({...m,recipients:undefined,readBy:m.readBy.filter(id=>id===actor.id||id==='admin')}))}}
