import {env} from 'cloudflare:workers';
import {getChatGPTUser} from '@/app/chatgpt-auth';
import {seed,type State} from '@/lib/domain';
import {applyCommand,type Command} from '@/lib/operations';
export const dynamic='force-dynamic';
const json=(value:unknown,status=200)=>Response.json(value,{status,headers:{'Cache-Control':'no-store'}});
async function context(req:Request){const user=await getChatGPTUser();if(!user)return null;const team=new URL(req.url).searchParams.get('team')||user.userId;const row=await env.DB.prepare('SELECT * FROM workspaces WHERE id = ?').bind(team).first<{id:string;owner:string;state:string;version:number}>();if(!row)return {user,team,row:null,state:null,actor:{id:'admin',admin:true}};const state=JSON.parse(row.state) as State;const admin=row.owner===user.userId;const employee=state.employees.find(e=>e.email&&e.email.toLowerCase()===user.email.toLowerCase());if(!admin&&!employee)throw new Error('접근 권한이 없습니다. 관리자에게 등록된 이메일을 확인하세요.');return {user,team,row,state,actor:{id:admin?'admin':employee!.id,admin}}}
function visible(state:State,actor:{id:string;admin:boolean}){if(actor.admin)return state;return {...state,employees:state.employees.map(e=>e.id===actor.id?e:{...e,email:'',rate:0}),shifts:state.published?state.shifts:[],attendance:state.attendance.filter(a=>a.employeeId===actor.id),swaps:state.swaps.filter(r=>r.from===actor.id||r.to===actor.id),messages:state.messages.filter(m=>m.to==='all'||m.to===actor.id||m.sender===actor.id)}}
export async function GET(req:Request){try{const c=await context(req);if(!c)return json({error:'로그인이 필요합니다.'},401);if(!c.row)return json({setup:true,team:c.user.userId,actor:c.actor});return json({state:visible(c.state!,c.actor),version:c.row.version,team:c.team,actor:c.actor})}catch(e){return json({error:e instanceof Error?e.message:'불러오지 못했습니다.'},403)}}
export async function POST(req:Request){try{const origin=req.headers.get('origin');if(origin&&origin!==new URL(req.url).origin)return json({error:'허용되지 않은 요청입니다.'},403);if(Number(req.headers.get('content-length')||0)>1500000)return json({error:'요청이 너무 큽니다.'},413);const c=await context(req);if(!c)return json({error:'로그인이 필요합니다.'},401);const body=await req.json() as Command&{version?:number};if(body.type==='initialize'){if(c.row||c.team!==c.user.userId)return json({error:'이미 생성되었거나 권한이 없습니다.'},409);const state=seed();state.shifts=[];await env.DB.prepare('INSERT INTO workspaces (id,owner,state,version) VALUES (?,?,?,1)').bind(c.user.userId,c.user.userId,JSON.stringify(state)).run();return json({state,version:1,team:c.user.userId,actor:c.actor})}if(!c.row||!c.state)return json({error:'워크스페이스를 먼저 생성하세요.'},400);if(body.version!==c.row.version)return json({error:'다른 사용자가 변경했습니다. 새로고침 후 다시 시도하세요.'},409);const state=applyCommand(c.state,body,c.actor);const result=await env.DB.prepare('UPDATE workspaces SET state = ?, version = version + 1 WHERE id = ? AND version = ?').bind(JSON.stringify(state),c.team,c.row.version).run();if(result.meta.changes!==1)return json({error:'동시 변경이 감지되었습니다. 다시 불러오세요.'},409);return json({state:visible(state,c.actor),version:c.row.version+1,team:c.team,actor:c.actor})}catch(e){return json({error:e instanceof Error?e.message:'저장하지 못했습니다.'},400)}}
